In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objects as go
import os 
import numpy as np

from datetime import datetime

import ccxt
import warnings
import seaborn as sns

warnings.filterwarnings('ignore')

In [3]:
import pandas as pd

def aggregate_timeframe(data, interval):
    """
    Agrège les données 1 minute en un intervalle personnalisé (par exemple, 3 minutes, 5 minutes, etc.).
    """
    aggregated = data.resample(interval).agg({
        'open': 'first',  #1ere val
        'high': 'max',     #val max
        'low': 'min',      # val min
        'close': 'last',   # last val
        'volume': 'sum'    #somme de l'intervalle
    })
    aggregated.dropna(inplace=True)  
    return aggregated

In [11]:
df_btc_1min = pd.read_parquet("/home/tsereir/tsereir/projets/algorithmic_trading/1min_perp/BTC_USDT_USDT.parquet")
df_btc_1min = df_btc_1min.set_index('date')
# df_btc_1min['date'] = pd.to_datetime(df_btc_1min['date'])

In [6]:
df_eth_1min = pd.read_parquet(r"C:\Users\tariq\algorithmic_trading\1min_perp\ETH_USDT_USDT.parquet")
df_eth_1min = df_eth_1min.set_index('date')
df_eth_3min = aggregate_timeframe(df_eth_1min, '3T')

df_eth_3min.reset_index().to_parquet(r"C:\Users\tariq\algorithmic_trading\3min_perp\ETH_USDT_USDT.parquet")

In [7]:
df_eth_7min = aggregate_timeframe(df_eth_1min, '7T')
df_eth_7min.reset_index().to_parquet(r"C:\Users\tariq\algorithmic_trading\7min_perp\ETH_USDT_USDT.parquet")

In [8]:
df_eth_10min = aggregate_timeframe(df_eth_1min, '10T')
df_eth_10min.reset_index().to_parquet(r"C:\Users\tariq\algorithmic_trading\10min_perp\ETH_USDT_USDT.parquet")
df_eth_15min = aggregate_timeframe(df_eth_1min, '15T')
df_eth_15min.reset_index().to_parquet(r"C:\Users\tariq\algorithmic_trading\15min_perp\ETH_USDT_USDT.parquet")

In [19]:
df_eth_5min = aggregate_timeframe(df_eth_1min, '5T')

In [20]:
df_eth_5min

                        open     high      low    close     volume
date
2020-01-01 00:00:00   129.12   129.12   128.76   128.81   2438.197
2020-01-01 00:05:00   128.78   128.94   128.65   128.87   2126.484
2020-01-01 00:10:00   128.90   128.92   128.77   128.87    888.920
2020-01-01 00:15:00   128.88   128.99   128.77   128.82   1570.849
2020-01-01 00:20:00   128.81   128.85   128.66   128.67    621.585
...                      ...      ...      ...      ...        ...
2025-04-07 08:45:00  1504.84  1509.00  1500.71  1501.00  55630.174
2025-04-07 08:50:00  1501.00  1501.12  1493.91  1496.59  63754.815
2025-04-07 08:55:00  1496.60  1502.36  1493.00  1495.05  39486.671
2025-04-07 09:00:00  1495.04  1501.64  1493.00  1497.46  38523.430
2025-04-07 09:05:00  1497.46  1497.57  1487.87  1489.08  42337.741

[553934 rows x 5 columns]

In [21]:
df_eth_5min.to_parquet("/home/tsereir/tsereir/projets/algorithmic_trading/5min_perp/ETH_USDT_USDT.parquet")

In [14]:
# df_btc_1min['date'] = pd.to_datetime(df_btc_1min['date'])
df_btc_5min = aggregate_timeframe(df_btc_1min, '5T')

In [16]:
df_btc_1min

                         open      high       low     close   volume
date
2020-01-01 00:00:00   7189.43   7190.52   7177.00   7182.44  246.092
2020-01-01 00:01:00   7182.43   7182.44   7178.75   7179.01   70.909
2020-01-01 00:02:00   7179.01   7179.01   7175.25   7177.93   99.420
2020-01-01 00:03:00   7177.77   7182.60   7177.00   7181.11   69.330
2020-01-01 00:04:00   7179.10   7179.10   7172.94   7175.25   97.368
...                       ...       ...       ...       ...      ...
2025-04-07 09:15:00  76075.80  76094.80  75996.80  76041.30  479.975
2025-04-07 09:16:00  76041.30  76086.50  75965.10  76026.00  620.153
2025-04-07 09:17:00  76026.00  76059.80  75903.30  75920.10  441.215
2025-04-07 09:18:00  75920.10  75972.60  75820.00  75822.60  612.508
2025-04-07 09:19:00  75822.60  75840.00  75800.30  75802.10  253.043

[2772452 rows x 5 columns]

In [17]:
df_btc_5min.to_parquet("/home/tsereir/tsereir/projets/algorithmic_trading/5min_perp/BTC_USDT_USDT.parquet")